baseURL = 'https://pfa.aytonprimary.com'
languageCode = 'en-gb'
title = 'Ayton Primary School PFA'
disableKinds = ["taxonomy", "taxonomyTerm"]
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = 'cms/pfa.yml'
target = 'assets/admin/config.yml'
