baseURL = 'https://aytonprimary.com'
languageCode = 'en-gb'
disableHugoGeneratorInject = true
title = 'Ayton Primary School'
disableKinds = ['taxonomy', 'taxonomyTerm']
[permalinks]
pfa-minutes = '/pfa/minutes/:year-:month-:day'
[markup.goldmark.renderer]
unsafe = true
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = 'cms/main.yml'
target = 'assets/admin/config.yml'
