[build]
publish = "public"

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[[headers]]
  for = "/*.woff2"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''
