[build]
publish = "public"
command = "hugo --minify --environment=production"
ignore = "[ $CACHED_COMMIT_REF != $COMMIT_REF ] && git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ./ ../common/"

[build.environment]
HUGO_VERSION = "0.119.0"

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[[headers]]
  for = "/*.woff2"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/i/*/*.*.*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/style.*.css"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''
