[build]
publish = "public"
command = "hugo --minify --environment=production"
ignore = "[ $CACHED_COMMIT_REF != $COMMIT_REF ] && git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ./ ../common/"

[build.environment]
HUGO_VERSION = "0.143.1"

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true
