[build]
publish = "public"
command = "hugo --minify --environment=production"
ignore = "[ -n \"$CACHED_COMMIT_REF\" ] && git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../common/"

[build.environment]
HUGO_VERSION = "0.106.0"

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true
