baseURL = 'https://ninjas.aytonprimary.com'
languageCode = 'en-gb'
title = 'Digital Ninjas'
disableKinds = ["taxonomy", "home"]
disableHugoGeneratorInject = true
[module]
[[module.mounts]]
source = 'layouts'
target = 'layouts'
[[module.mounts]]
source = '../common/cms.html'
target = 'layouts/cms/baseof.html'
